# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5a9a0dde1957fcdfb78b02674e51a955"
name = "StickerPulse Product Labels"
application_url = "https://sticker-pulse-product-label.vercel.app"
embedded = true
handle = "stickerpulse-product-labels"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes,write_products"

[auth]
redirect_urls = [ "https://sticker-pulse-product-label.vercel.app/api/auth/callback" ]

[pos]
embedded = false
